#ifndef __SYMBOL_H__
#define __SYMBOL_H__

enum symbol {
    ADD = 21, SUBTRACT, MULTIPLY, DIVIDE, EQ_TWO, EQ, L_BRACE, R_BRACE, BIGGER_EQ, BIGGER, SMALLER_EQ, SMALLER, L_PARENTHESIS, R_PARENTHESIS, SEMICOLON, START_END
};

#endif